# Generated by Django 4.0.4 on 2022-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rqapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_contents',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='FRS', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
